fixtures:
  #forge_modules:
  #  windowsfeature:
  #    repo:  "puppet/windowsfeature"
  #    ref:   "1.1.0"
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
  symlinks:
      bnsiis: "#{source_dir}"
